### PR TITLE
Allow for alternate dragon invocations

### PR DESCRIPTION
**Pull request by stsquad**
At least when building dragon from source the binary is called "dragon" and not "dragon-drop".

### CODE REVIEW

**Comment by moverest** [comment]
Indeed, this is more of a Arch Linux specific naming as it conflicts with another application's name &mdash; see [`dragon-drop`](https://aur.archlinux.org/packages/dragon-drop) AUR package and https://github.com/mwh/dragon/issues/17.

So we might want to try either a fallback or adding this as part of the configuration, e.g.:

```toml
[notification_actions]
dragon.command = "dragon"
````

**Comment by stsquad** [comment]
I've got a partial patch but I'm a little unclear on the best way to plumb the configuration option into the action.

```
modified   sway-interactive-screenshot
@@ -99,6 +99,9 @@ class Config:
             "file_name": "screencast_%Y-%m-%dT%H:%M:%S.mkv",
             "audio": "ask",
         },
+        "notification_actions": {
+            "dragon.command": "dragon",
+        }
     }
 
     _validate = staticmethod(
@@ -124,6 +127,11 @@ class Config:
                         "audio": config_enum_validator({"yes", "no", "ask"}),
                     }
                 ),
+                "notification_actions": config_dict_validator(
+                    {
+                        "dragon.command": config_enum_validator({"dragon", "dragon-drop"}),
+                    }
+                )
             }
         )
     )
```

**Comment by moverest** [comment]
Yeah, you got the idea. :+1: 

The following TOML:

```toml
[notification_actions]
dragon.command = "dragon"
```

Will produce this:

```json
{
  "notification_actions": {
    "dragon": {
      "command": "dragon"
    }
  }
}
```

So then, it's only a question of adding the validation and the default value (as you did but with the nested dictionary):

```diff
diff --git a/sway-interactive-screenshot b/sway-interactive-screenshot
index 3e5c406..6a6f86d 100755
--- a/sway-interactive-screenshot
+++ b/sway-interactive-screenshot
@@ -99,6 +99,11 @@ class Config:
             "file_name": "screencast_%Y-%m-%dT%H:%M:%S.mkv",
             "audio": "ask",
         },
+        "notification_actions": {
+            "dragon": {
+                "command": "dragon-drop",
+            }
+        },
     }
 
     _validate = staticmethod(
@@ -124,6 +129,15 @@ class Config:
                         "audio": config_enum_validator({"yes", "no", "ask"}),
                     }
                 ),
+                "notification_actions": config_dict_validator(
+                    {
+                        "dragon": config_dict_validator(
+                            {
+                                "command": config_type_validator(str),
+                            }
+                        )
+                    }
+                ),
             }
         )
     )

```

And then inject that into the `NotificationAction.run()` method:
```diff
diff --git a/sway-interactive-screenshot b/sway-interactive-screenshot
index 3e5c406..3b6f429 100755
--- a/sway-interactive-screenshot
+++ b/sway-interactive-screenshot
@@ -517,7 +517,7 @@ class NotificationAction(abc.ABC):
 
     @classmethod
     @abc.abstractmethod
-    def run(cls, *, filepath: Path) -> None:
+    def run(cls, *, filepath: Path, config_getter: Callable[[str], Any]) -> None:
         pass
 
 
@@ -526,7 +526,7 @@ class EditNotificationAction(NotificationAction):
     description = "Edit"
 
     @classmethod
-    def run(cls, *, filepath: Path) -> None:
+    def run(cls, *, filepath: Path, config_getter: Callable[[str], Any]) -> None:
         filepath_str = str(filepath.expanduser())
         edit_capture(filepath_str)
         copy_file_to_clipboard(filepath_str)
@@ -537,7 +537,7 @@ class DeleteNotificationAction(NotificationAction):
     description = "Delete"
 
     @classmethod
-    def run(cls, *, filepath: Path) -> None:
+    def run(cls, *, filepath: Path, config_getter: Callable[[str], Any]) -> None:
         filepath.expanduser().unlink()
         notify("Deleted")
 
@@ -547,8 +547,8 @@ class DragonNotificationAction(NotificationAction):
     description = "Drag and drop"
 
     @classmethod
-    def run(cls, *, filepath: Path) -> None:
-        subprocess.run(["dragon-drop", filepath.expanduser()], check=False)
+    def run(cls, *, filepath: Path, config_getter: Callable[[str], Any]) -> None:
+        subprocess.run([config_getter("command"), filepath.expanduser()], check=False)
 
 
 class OpenNotificationAction(NotificationAction):
@@ -556,7 +556,7 @@ class OpenNotificationAction(NotificationAction):
     description = "Open"
 
     @classmethod
-    def run(cls, *, filepath: Path) -> None:
+    def run(cls, *, filepath: Path, config: Dict[str, Any]) -> None:
         subprocess.run(["xdg-open", filepath.expanduser()], check=False)
 
 
@@ -801,7 +801,10 @@ def main():
         )
 
         if action is not None:
-            action.run(filepath=filepath)
+            action.run(
+                filepath=filepath,
+                config_getter=partial(config.get, "notification_actions", action.name),
+            )
 
     except Exception as err:  # pylint: disable=broad-except
         display_name = (
```

**Comment by stsquad** [comment]
@moverest thanks, I've pushed an update with a config driven flow.

**Review by moverest — APPROVED** [review]

**Comment by moverest** [comment]
Merged now. Thanks for your contribution @stsquad!

**Pull request merged**
